apiVersion: v1
kind: Service
metadata:
    name: wordpress
    labels:
        app: wordpress
spec:
    ports:
        - port: 80
    selector:
        app: wordpress
        tier: frontend
    type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: wp-pv-claim
    labels:
        app: wordpress
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: wordpress
    labels:
        app: wordpress
spec:
    selector:
        matchLabels:
            app: wordpress
            tier: frontend
    strategy:
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: wordpress
                tier: frontend
        spec:
            containers:
                - image: wordpress:4.8-apache
                  name: wordpress
                  readinessProbe:
                      httpGet:
                          path: /wp-admin/install.php
                          port: 80
                      initialDelaySeconds: 30
                      periodSeconds: 10
                  livenessProbe:
                      httpGet:
                          path: /wp-admin/install.php
                          port: 80
                      initialDelaySeconds: 30
                      periodSeconds: 10
                  env:
                      - name: WORDPRESS_DB_HOST
                        value: wordpress-mysql
                      - name: WORDPRESS_DB_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: mysql-pass
                                key: password
                  ports:
                      - containerPort: 80
                        name: wordpress
                  resources:
                      requests:
                          memory: "32Mi"
                          cpu: "200m"
                      limits:
                          memory: "64Mi"
                          cpu: "250m"
                  volumeMounts:
                      - name: wordpress-persistent-storage
                        mountPath: /var/www/html
            volumes:
                - name: wordpress-persistent-storage
                  persistentVolumeClaim:
                      claimName: wp-pv-claim
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: wordpress-hpa
    labels:
        app: wordpress
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: wordpress
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 75
---
kind: Service
apiVersion: v1
metadata:
    name: wordpress-svc
spec:
    type: NodePort
    selector:
        app: wordpress
    ports:
        - port: 80
          targetPort: 80
          nodePort: 30080
